import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { ProjectsService } from './projects.service';
import { Result, ok, err } from '@kamaia/shared-types';
import { GenerateReportDto, UpdateReportDto } from './projects.dto';

/**
 * Weekly status reports — one row per project per week (keyed by the
 * Monday of that week, UTC). Rows are autogenerated by a cron on Monday
 * mornings and can also be created/edited on demand by users.
 *
 * Each report captures:
 *  - Health status (green/yellow/red) — defaults from burndown ratio but
 *    overridable by the user
 *  - Budget snapshot (budget, actualSpent, idealSpent from burndown)
 *  - Milestone KPIs (total, completed, overdue)
 *  - Hours logged that week
 *  - Narrative (summary + risks array)
 */
@Injectable()
export class ProjectReportsService {
  private readonly logger = new Logger(ProjectReportsService.name);

  constructor(
    private prisma: PrismaService,
    private projectsService: ProjectsService,
  ) {}

  /** Monday 08:00 UTC every week. */
  @Cron('0 8 * * 1')
  async weeklyScheduledReports() {
    this.logger.log('Running weekly project status reports');
    await this.generateAll();
  }

  /**
   * Generates a report for every active project. Skips projects that
   * already have a report for the current week (idempotent).
   */
  async generateAll(): Promise<{ generated: number; skipped: number }> {
    const projects = await this.prisma.project.findMany({
      where: { deletedAt: null, status: { in: ['ACTIVO', 'PROPOSTA'] } },
      select: { id: true, gabineteId: true, managerId: true },
    });
    let generated = 0;
    let skipped = 0;
    const weekStart = this.mondayOfWeek(new Date());
    for (const p of projects) {
      const existing = await this.prisma.projectStatusReport.findFirst({
        where: { projectId: p.id, weekStart, deletedAt: null },
      });
      if (existing) {
        skipped++;
        continue;
      }
      const r = await this.generate(p.gabineteId, p.managerId, p.id, { weekStart: weekStart.toISOString() });
      if (r.success) generated++;
    }
    return { generated, skipped };
  }

  async list(gabineteId: string, projectId: string): Promise<Result<any[]>> {
    try {
      const project = await this.prisma.project.findFirst({
        where: { id: projectId, gabineteId, deletedAt: null },
        select: { id: true },
      });
      if (!project) return err('Project not found', 'PROJECT_NOT_FOUND');

      const reports = await this.prisma.projectStatusReport.findMany({
        where: { projectId, deletedAt: null },
        orderBy: { weekStart: 'desc' },
        include: {
          createdBy: { select: { id: true, firstName: true, lastName: true } },
        },
      });
      return ok(reports);
    } catch (e) {
      return err('Failed to list reports', 'REPORTS_LIST_FAILED');
    }
  }

  async generate(
    gabineteId: string,
    userId: string,
    projectId: string,
    dto: GenerateReportDto,
  ): Promise<Result<any>> {
    try {
      const project = await this.prisma.project.findFirst({
        where: { id: projectId, gabineteId, deletedAt: null },
      });
      if (!project) return err('Project not found', 'PROJECT_NOT_FOUND');

      const weekStart = dto.weekStart
        ? this.mondayOfWeek(new Date(dto.weekStart))
        : this.mondayOfWeek(new Date());
      const weekEnd = new Date(weekStart.getTime() + 7 * 86_400_000);

      // Pull burndown snapshot (source of truth for spend numbers)
      const burndown = await this.projectsService.getBurndown(gabineteId, projectId);
      const b = burndown.success ? (burndown.data as any) : null;
      const todayKey = new Date().toISOString().slice(0, 10);
      const point =
        b?.series?.find((s: any) => s.date === todayKey) ??
        b?.series?.[b?.series?.length - 1] ??
        null;

      // Milestones KPIs
      const [total, completed, overdue] = await Promise.all([
        this.prisma.projectMilestone.count({ where: { projectId, deletedAt: null } }),
        this.prisma.projectMilestone.count({
          where: { projectId, deletedAt: null, completedAt: { not: null } },
        }),
        this.prisma.projectMilestone.count({
          where: {
            projectId,
            deletedAt: null,
            completedAt: null,
            dueDate: { lt: new Date() },
          },
        }),
      ]);

      // Hours logged this week (across linked processos)
      const linkedProcessos = await this.prisma.processo.findMany({
        where: { projectId, gabineteId },
        select: { id: true },
      });
      const processoIds = linkedProcessos.map((p) => p.id);
      const entries = processoIds.length
        ? await this.prisma.timeEntry.findMany({
            where: {
              processoId: { in: processoIds },
              date: { gte: weekStart, lt: weekEnd },
            },
            select: { durationMinutes: true },
          })
        : [];
      const hoursLoggedMinutes = entries.reduce((s, e) => s + e.durationMinutes, 0);

      // Derive health from burndown ratio unless user overrides
      const derivedHealth = this.deriveHealth(point, overdue);

      const report = await this.prisma.projectStatusReport.upsert({
        where: { projectId_weekStart: { projectId, weekStart } },
        create: {
          projectId,
          weekStart,
          healthStatus: dto.healthStatus ?? derivedHealth,
          budgetSnapshot: b?.budget ?? null,
          actualSpentSnapshot: point?.actualSpent ?? null,
          idealSpentSnapshot: point?.idealSpent ?? null,
          hoursLoggedMinutes,
          milestonesTotal: total,
          milestonesCompleted: completed,
          milestonesOverdue: overdue,
          risks: (dto.risks ?? []) as any,
          summary: dto.summary ?? null,
          createdById: userId,
        },
        update: {
          healthStatus: dto.healthStatus ?? derivedHealth,
          budgetSnapshot: b?.budget ?? null,
          actualSpentSnapshot: point?.actualSpent ?? null,
          idealSpentSnapshot: point?.idealSpent ?? null,
          hoursLoggedMinutes,
          milestonesTotal: total,
          milestonesCompleted: completed,
          milestonesOverdue: overdue,
          ...(dto.risks !== undefined && { risks: (dto.risks ?? []) as any }),
          ...(dto.summary !== undefined && { summary: dto.summary }),
          // Resurrect if previously soft-deleted (same week regenerated).
          deletedAt: null,
        },
      });

      return ok(report);
    } catch (e) {
      return err('Failed to generate report', 'REPORT_GENERATE_FAILED');
    }
  }

  async update(
    gabineteId: string,
    reportId: string,
    dto: UpdateReportDto,
  ): Promise<Result<any>> {
    try {
      const report = await this.prisma.projectStatusReport.findFirst({
        where: { id: reportId, project: { gabineteId }, deletedAt: null },
      });
      if (!report) return err('Report not found', 'REPORT_NOT_FOUND');

      const updated = await this.prisma.projectStatusReport.update({
        where: { id: reportId },
        data: {
          ...(dto.healthStatus !== undefined && { healthStatus: dto.healthStatus }),
          ...(dto.summary !== undefined && { summary: dto.summary }),
          ...(dto.risks !== undefined && { risks: (dto.risks ?? []) as any }),
        },
      });
      return ok(updated);
    } catch (e) {
      return err('Failed to update report', 'REPORT_UPDATE_FAILED');
    }
  }

  /**
   * Renders a status report to a PDF buffer using pdfkit. The output is
   * a portable A4 document suitable for emailing to a client or sponsor.
   */
  async exportPdf(
    gabineteId: string,
    reportId: string,
  ): Promise<Result<Buffer>> {
    try {
      const report = await this.prisma.projectStatusReport.findFirst({
        where: { id: reportId, project: { gabineteId }, deletedAt: null },
        include: {
          project: {
            select: {
              name: true,
              code: true,
              category: true,
              cliente: { select: { name: true } },
            },
          },
          createdBy: { select: { firstName: true, lastName: true } },
        },
      });
      if (!report) return err('Report not found', 'REPORT_NOT_FOUND');

      // Dynamic import keeps pdfkit out of the main bundle path
      const PDFDocument = (await import('pdfkit')).default;
      const doc = new PDFDocument({ size: 'A4', margin: 48 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      const done = new Promise<Buffer>((resolve) => {
        doc.on('end', () => resolve(Buffer.concat(chunks)));
      });

      // Header
      doc.fontSize(10).fillColor('#737373').text('KAMAIA · STATUS REPORT');
      doc.moveDown(0.3);
      doc.fontSize(20).fillColor('#111').text(report.project.name);
      doc
        .fontSize(10)
        .fillColor('#737373')
        .text(
          `${report.project.code} · ${report.project.category}${report.project.cliente ? ` · ${report.project.cliente.name}` : ''}`,
        );
      doc.moveDown(0.5);
      doc
        .fontSize(11)
        .fillColor('#111')
        .text(
          `Semana de ${new Date(report.weekStart).toLocaleDateString('pt-AO', {
            day: '2-digit',
            month: 'long',
            year: 'numeric',
          })}`,
        );
      doc.moveDown(1);

      // Health badge
      const healthColors: Record<string, string> = {
        GREEN: '#16A34A',
        YELLOW: '#D97706',
        RED: '#DC2626',
      };
      const healthLabel: Record<string, string> = {
        GREEN: 'SAUDÁVEL',
        YELLOW: 'ATENÇÃO',
        RED: 'CRÍTICO',
      };
      doc
        .fontSize(12)
        .fillColor(healthColors[report.healthStatus] ?? '#111')
        .text(`Estado: ${healthLabel[report.healthStatus] ?? report.healthStatus}`);
      doc.moveDown(1);

      // KPI grid
      doc.fontSize(11).fillColor('#111').text('Indicadores da semana', { underline: true });
      doc.moveDown(0.3);
      const rows: Array<[string, string]> = [
        ['Horas logadas', `${(report.hoursLoggedMinutes / 60).toFixed(1)}h`],
        ['Marcos', `${report.milestonesCompleted}/${report.milestonesTotal}`],
        ['Atrasados', `${report.milestonesOverdue}`],
      ];
      if (report.budgetSnapshot != null && report.budgetSnapshot > 0) {
        rows.push([
          'Orçamento',
          `${(report.budgetSnapshot / 100).toLocaleString('pt-AO')} AOA`,
        ]);
        rows.push([
          'Gasto real',
          `${((report.actualSpentSnapshot ?? 0) / 100).toLocaleString('pt-AO')} AOA`,
        ]);
        rows.push([
          'Ideal à data',
          `${((report.idealSpentSnapshot ?? 0) / 100).toLocaleString('pt-AO')} AOA`,
        ]);
      }
      for (const [k, v] of rows) {
        doc.fontSize(10).fillColor('#737373').text(k, { continued: true, width: 160 });
        doc.fillColor('#111').text(`  ${v}`);
      }
      doc.moveDown(1);

      // Summary
      if (report.summary) {
        doc.fontSize(11).fillColor('#111').text('Sumário', { underline: true });
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#333').text(report.summary, { align: 'left' });
        doc.moveDown(1);
      }

      // Risks
      const risks = Array.isArray(report.risks) ? (report.risks as any[]) : [];
      if (risks.length > 0) {
        doc.fontSize(11).fillColor('#111').text('Riscos', { underline: true });
        doc.moveDown(0.3);
        for (const r of risks) {
          doc
            .fontSize(10)
            .fillColor(
              r.severity === 'CRITICAL'
                ? '#DC2626'
                : r.severity === 'HIGH'
                  ? '#EA580C'
                  : r.severity === 'MEDIUM'
                    ? '#D97706'
                    : '#737373',
            )
            .text(`[${r.severity}] `, { continued: true });
          doc.fillColor('#111').text(r.title);
          if (r.mitigation) {
            doc.fontSize(9).fillColor('#737373').text(`Mitigação: ${r.mitigation}`);
          }
          doc.moveDown(0.3);
        }
      }

      // Footer
      doc.moveDown(1.5);
      doc.fontSize(8).fillColor('#A3A3A3').text(
        `Gerado por ${report.createdBy.firstName} ${report.createdBy.lastName} · ${new Date(report.createdAt).toLocaleDateString('pt-AO')}`,
        { align: 'right' },
      );

      doc.end();
      const buffer = await done;
      return ok(buffer);
    } catch (e) {
      return err('Failed to export PDF', 'REPORT_PDF_FAILED');
    }
  }

  async delete(gabineteId: string, reportId: string): Promise<Result<void>> {
    try {
      const report = await this.prisma.projectStatusReport.findFirst({
        where: { id: reportId, project: { gabineteId }, deletedAt: null },
      });
      if (!report) return err('Report not found', 'REPORT_NOT_FOUND');
      await this.prisma.projectStatusReport.update({
        where: { id: reportId },
        data: { deletedAt: new Date() },
      });
      return ok(undefined);
    } catch (e) {
      return err('Failed to delete report', 'REPORT_DELETE_FAILED');
    }
  }

  /** Monday of the given week in UTC, normalized to 00:00. */
  private mondayOfWeek(d: Date): Date {
    const x = new Date(d);
    x.setUTCHours(0, 0, 0, 0);
    const day = x.getUTCDay();
    const delta = (day + 6) % 7; // Mon=0 after shift
    x.setUTCDate(x.getUTCDate() - delta);
    return x;
  }

  /**
   * Derives health from burndown + overdue count. Users can override.
   *  - RED when spend > ideal × 1.25 OR at least 1 overdue milestone is
   *    more than 2 weeks late (indicated by count ≥ 3 proxy).
   *  - YELLOW when spend > ideal × 1.10 OR any overdue milestone.
   *  - GREEN otherwise.
   */
  private deriveHealth(
    point: { actualSpent: number; idealSpent: number } | null,
    overdue: number,
  ): 'GREEN' | 'YELLOW' | 'RED' {
    const ratio = point && point.idealSpent > 0 ? point.actualSpent / point.idealSpent : 0;
    if (ratio > 1.25 || overdue >= 3) return 'RED';
    if (ratio > 1.1 || overdue > 0) return 'YELLOW';
    return 'GREEN';
  }
}
