import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { ProjectsService } from './projects.service';
import { Result, ok, err } from '@kamaia/shared-types';
import { GenerateReportDto, UpdateReportDto } from './projects.dto';

/**
 * Weekly status reports — one row per project per week (keyed by the
 * Monday of that week, UTC). Rows are autogenerated by a cron on Monday
 * mornings and can also be created/edited on demand by users.
 *
 * Each report captures:
 *  - Health status (green/yellow/red) — defaults from burndown ratio but
 *    overridable by the user
 *  - Budget snapshot (budget, actualSpent, idealSpent from burndown)
 *  - Milestone KPIs (total, completed, overdue)
 *  - Hours logged that week
 *  - Narrative (summary + risks array)
 */
@Injectable()
export class ProjectReportsService {
  private readonly logger = new Logger(ProjectReportsService.name);

  constructor(
    private prisma: PrismaService,
    private projectsService: ProjectsService,
  ) {}

  /** Monday 08:00 UTC every week. */
  @Cron('0 8 * * 1')
  async weeklyScheduledReports() {
    this.logger.log('Running weekly project status reports');
    await this.generateAll();
  }

  /**
   * Generates a report for every active project. Skips projects that
   * already have a report for the current week (idempotent).
   */
  async generateAll(): Promise<{ generated: number; skipped: number }> {
    const projects = await this.prisma.project.findMany({
      where: { deletedAt: null, status: { in: ['ACTIVO', 'PROPOSTA'] } },
      select: { id: true, gabineteId: true, managerId: true },
    });
    let generated = 0;
    let skipped = 0;
    const weekStart = this.mondayOfWeek(new Date());
    for (const p of projects) {
      const existing = await this.prisma.projectStatusReport.findUnique({
        where: { projectId_weekStart: { projectId: p.id, weekStart } },
      });
      if (existing) {
        skipped++;
        continue;
      }
      const r = await this.generate(p.gabineteId, p.managerId, p.id, { weekStart: weekStart.toISOString() });
      if (r.success) generated++;
    }
    return { generated, skipped };
  }

  async list(gabineteId: string, projectId: string): Promise<Result<any[]>> {
    try {
      const project = await this.prisma.project.findFirst({
        where: { id: projectId, gabineteId, deletedAt: null },
        select: { id: true },
      });
      if (!project) return err('Project not found', 'PROJECT_NOT_FOUND');

      const reports = await this.prisma.projectStatusReport.findMany({
        where: { projectId },
        orderBy: { weekStart: 'desc' },
        include: {
          createdBy: { select: { id: true, firstName: true, lastName: true } },
        },
      });
      return ok(reports);
    } catch (e) {
      return err('Failed to list reports', 'REPORTS_LIST_FAILED');
    }
  }

  async generate(
    gabineteId: string,
    userId: string,
    projectId: string,
    dto: GenerateReportDto,
  ): Promise<Result<any>> {
    try {
      const project = await this.prisma.project.findFirst({
        where: { id: projectId, gabineteId, deletedAt: null },
      });
      if (!project) return err('Project not found', 'PROJECT_NOT_FOUND');

      const weekStart = dto.weekStart
        ? this.mondayOfWeek(new Date(dto.weekStart))
        : this.mondayOfWeek(new Date());
      const weekEnd = new Date(weekStart.getTime() + 7 * 86_400_000);

      // Pull burndown snapshot (source of truth for spend numbers)
      const burndown = await this.projectsService.getBurndown(gabineteId, projectId);
      const b = burndown.success ? (burndown.data as any) : null;
      const todayKey = new Date().toISOString().slice(0, 10);
      const point =
        b?.series?.find((s: any) => s.date === todayKey) ??
        b?.series?.[b?.series?.length - 1] ??
        null;

      // Milestones KPIs
      const [total, completed, overdue] = await Promise.all([
        this.prisma.projectMilestone.count({ where: { projectId } }),
        this.prisma.projectMilestone.count({
          where: { projectId, completedAt: { not: null } },
        }),
        this.prisma.projectMilestone.count({
          where: { projectId, completedAt: null, dueDate: { lt: new Date() } },
        }),
      ]);

      // Hours logged this week (across linked processos)
      const linkedProcessos = await this.prisma.processo.findMany({
        where: { projectId, gabineteId },
        select: { id: true },
      });
      const processoIds = linkedProcessos.map((p) => p.id);
      const entries = processoIds.length
        ? await this.prisma.timeEntry.findMany({
            where: {
              processoId: { in: processoIds },
              date: { gte: weekStart, lt: weekEnd },
            },
            select: { durationMinutes: true },
          })
        : [];
      const hoursLoggedMinutes = entries.reduce((s, e) => s + e.durationMinutes, 0);

      // Derive health from burndown ratio unless user overrides
      const derivedHealth = this.deriveHealth(point, overdue);

      const report = await this.prisma.projectStatusReport.upsert({
        where: { projectId_weekStart: { projectId, weekStart } },
        create: {
          projectId,
          weekStart,
          healthStatus: dto.healthStatus ?? derivedHealth,
          budgetSnapshot: b?.budget ?? null,
          actualSpentSnapshot: point?.actualSpent ?? null,
          idealSpentSnapshot: point?.idealSpent ?? null,
          hoursLoggedMinutes,
          milestonesTotal: total,
          milestonesCompleted: completed,
          milestonesOverdue: overdue,
          risks: (dto.risks ?? []) as any,
          summary: dto.summary ?? null,
          createdById: userId,
        },
        update: {
          healthStatus: dto.healthStatus ?? derivedHealth,
          budgetSnapshot: b?.budget ?? null,
          actualSpentSnapshot: point?.actualSpent ?? null,
          idealSpentSnapshot: point?.idealSpent ?? null,
          hoursLoggedMinutes,
          milestonesTotal: total,
          milestonesCompleted: completed,
          milestonesOverdue: overdue,
          ...(dto.risks !== undefined && { risks: (dto.risks ?? []) as any }),
          ...(dto.summary !== undefined && { summary: dto.summary }),
        },
      });

      return ok(report);
    } catch (e) {
      return err('Failed to generate report', 'REPORT_GENERATE_FAILED');
    }
  }

  async update(
    gabineteId: string,
    reportId: string,
    dto: UpdateReportDto,
  ): Promise<Result<any>> {
    try {
      const report = await this.prisma.projectStatusReport.findFirst({
        where: { id: reportId, project: { gabineteId } },
      });
      if (!report) return err('Report not found', 'REPORT_NOT_FOUND');

      const updated = await this.prisma.projectStatusReport.update({
        where: { id: reportId },
        data: {
          ...(dto.healthStatus !== undefined && { healthStatus: dto.healthStatus }),
          ...(dto.summary !== undefined && { summary: dto.summary }),
          ...(dto.risks !== undefined && { risks: (dto.risks ?? []) as any }),
        },
      });
      return ok(updated);
    } catch (e) {
      return err('Failed to update report', 'REPORT_UPDATE_FAILED');
    }
  }

  async delete(gabineteId: string, reportId: string): Promise<Result<void>> {
    try {
      const report = await this.prisma.projectStatusReport.findFirst({
        where: { id: reportId, project: { gabineteId } },
      });
      if (!report) return err('Report not found', 'REPORT_NOT_FOUND');
      await this.prisma.projectStatusReport.delete({ where: { id: reportId } });
      return ok(undefined);
    } catch (e) {
      return err('Failed to delete report', 'REPORT_DELETE_FAILED');
    }
  }

  /** Monday of the given week in UTC, normalized to 00:00. */
  private mondayOfWeek(d: Date): Date {
    const x = new Date(d);
    x.setUTCHours(0, 0, 0, 0);
    const day = x.getUTCDay();
    const delta = (day + 6) % 7; // Mon=0 after shift
    x.setUTCDate(x.getUTCDate() - delta);
    return x;
  }

  /**
   * Derives health from burndown + overdue count. Users can override.
   *  - RED when spend > ideal × 1.25 OR at least 1 overdue milestone is
   *    more than 2 weeks late (indicated by count ≥ 3 proxy).
   *  - YELLOW when spend > ideal × 1.10 OR any overdue milestone.
   *  - GREEN otherwise.
   */
  private deriveHealth(
    point: { actualSpent: number; idealSpent: number } | null,
    overdue: number,
  ): 'GREEN' | 'YELLOW' | 'RED' {
    const ratio = point && point.idealSpent > 0 ? point.actualSpent / point.idealSpent : 0;
    if (ratio > 1.25 || overdue >= 3) return 'RED';
    if (ratio > 1.1 || overdue > 0) return 'YELLOW';
    return 'GREEN';
  }
}
